<?php
namespace App\Models;
class AC extends User{
    //oneToMany=>inscription
    //premiere approche
    private array $inscription;
    //fonctions navigationnelles : 2nd approches
    public function inscriptions():array
    {
        return [];
    }

    public function __construct()
    {
        parent::$role="ROLE_AC";
        $this->inscription=[];
    }
// redefinition des methodes
    public static function findAll(): array
    {
        /* TODO : Change the autogenerated stub */
        $sql = "SELECT * FROM ".parent::table()." WHERE role like 'ROLE_AC'";
        return parent::findBy($sql,[]);
    }
    public function insert(): int
    {
        /*

        */
        $sql = "INSERT INTO ". parent::table() ." (`nom_complet`, `role`, `login`, `password`) VALUES (?,?,?,?)";
        $db = parent::database();
        $db->connexionBD();
        $res = $db->executeUpdate($sql,[$this->nomComplet,parent::$role,$this->login, $this->password]);
        $db->closeConnexion();
        return $res;
        //return parent::insert(); // TODO: Change the autogenerated stub
    }
}