<?php
namespace App\Models;
require_once ('../models/User.php');
class AC extends User{
    //oneToMany=>inscription
    //premiere approche
    private array $inscription;
    //fonctions navigationnelles : 2nd approches
    public function inscriptions():array
    {
        return [];
    }

    public function __construct()
    {
        $this->role="ROLE_AC";
        $this->inscription=[];
    }
// redefinition des methodes
    public static function findAll(): array
    {
        $sql = "SELECT * FROM ".self::$table." WHERE role like ".self::$role;
        return []; // TODO: Change the autogenerated stub
    }
}