<?php
namespace App\Models;
use App\Core\Model;
abstract class Personne extends Model {
    //atrubut d'instances
    protected int $id;
    protected string $nomComplet;
    protected static string $role;
    //1- attrubut de class ou d'instance, spécififique à chaque class
    private static int $nbrepersonne;

    //2- constructeur par defaut
    public function  __construct(){
         self::$table="personne";
    }

    public function getId():int
    {
        return $this->id;
    }
    public function setId($id) : void
    {
        $this->id = $id;
    }
    public function getNomComplet() : string
    {
        return $this->nomComplet;
    }
    public function setNomComplet($nomComplet) : self
    {
        $this->nomComplet = $nomComplet;
        return $this;
    }

    /**
     * @return int
     */
    public static function getNbrepersonne(): int
    {
        return self::$nbrepersonne;
    }

    /**
     * @param int $nbrepersonne
     */
    public static function setNbrepersonne(int $nbrepersonne): void
    {
        self::$nbrepersonne = $nbrepersonne;
    }

    public static function findAll(): array
    {
        // TODO: Change the autogenerated stub
        $sql = "SELECT * FROM personne";
        return parent::findBy($sql,[]);
    }
}