<?php
namespace App\Models;
use App\Core\Databases;

class Professeur extends  Personne{
   private string $grade;

    public function getGrade(): string
    {
        return $this->grade;
    }

    public function setGrade(string $grade): void
    {
        $this->grade = $grade;
    }
    public function __construct()
    {
        parent::$role="ROLE_PROFESSEUR";
    }
    //fonctions navigationnelles
    /*ManyToMany avec classe*/
    public function classes() : array
    {
        return [];
    }

    public static function findAll(): array
    {
        $sql = "SELECT * FROM ".parent::table()." WHERE role like 'ROLE_PROFESSEUR'";
        return parent::findBy($sql,[]);
    }

    public function insert(): int
    {
        $sql = "INSERT INTO `". parent::table() ."` (`nom_complet`, `role`,`grade`) VALUES (?,?,?)";
        $db = parent::database();
        $db->connexionBD();
        $res = $db->executeUpdate($sql,[$this->nomComplet,parent::$role,$this->grade]);
        $db->closeConnexion();
        return $res;
        //return parent::insert(); // TODO: Change the autogenerated stub
    }
}
