<?php
namespace App\Models;
class RP extends User {


    public function __construct()
    {
         self::$role="ROLE_RP";
    }
    public static function findAll(): array
    {
        $sql = "SELECT * FROM ".self::$table." WHERE role like ".self::$role;
        return []; // TODO: Change the autogenerated stub
    }
}